### ISSUE TITLE
Enhancement Request: Flair Negation

### ISSUE THREAD

**Issue by d-reddi** [fsvreddit/automodmail#19]
Enhancement request: 
Ability to use negation in `flair_text` and/or `flair_css_class`

Use Case: 

- Some subs have a process in which the user can be verified as a helpful user or a variety of other flairs. 
- Users may write in saying "i'm verified but it's not showing that I am when I post" 
- Auto-modmail responds with "You're not showing verified........follow these instructions to verify. If you have followed these already and believe it's an error, reply to this message."
---
- **Current Behavior for Auto-modmail:** Cannot recognize users with no flair or a different flair other than specified _exact_ text / css class
- **Enhanced Behavior for Auto-modmail:** Could recognize that a user does not have a specific flair **OR** flair is null.  (If negation is too difficult to build, perhaps having it recognize _null_ flair i.e., flair_text: "" or a custom {null} placeholder for flairs? 

Thanks for all your hard work on this, it's a brilliant tool!

**Comment by fsvreddit** [comment]
Hi! It shouldn't be a big deal to add negation and all the other search options (regex/includes/includes_word etc.) to the flair_text check as well as flair CSS class. I'll look to get that in in the 1.4 release (I don't want to pile more functionality in at a time that Admin might be mid-testing!).
