### ISSUE TITLE
Feature Request : allow modifiers for `action_reason:`

### ISSUE THREAD

**Issue by Munkenmo** [fsvreddit/automodmail#37]
/r/nrl has a lot of rules specific to our MatchThreads.

Some examples of action_reasons for these rules are :

* action_reason: 'Match Thread - not enough nrl karma'
* action_reason: 'Match Thread - L.karma possible ref bashing : "{{match}}"'
* action_reason: 'Match Thread - Probable ref bashing : "{{match}}"'
* action_reason: 'Match Thread - L.karma Ref named : "{{match}}"'

It would be helpful if we could have one Automodmail rule to catch responses to these, by enabling modifiers to the action_reason: 

eg.

* action_reason (regex): "^Match Thread -"
* action_reason (starts-with): "Match Thread"

`
body: ["removed", "not showing", "deleted", "banned", "hide", "hidden"]

Ideally this change would allow a rule like this :

    mod_action:
    moderator_name: "AutoModerator"
    mod_action_type: "removecomment"
    action_within: "60 minutes"
    action_reason (regex): "^Match Thread -"
    reply:  |

**Comment by fsvreddit** [comment]
Great idea, that should be easy enough to put in place. I'll get it into a future release.
